---
default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>
  min_messages: warning
  password: <%= ENV.fetch('DATABASE_PASSWORD', '') %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>
  port: <%= ENV.fetch('DATABASE_PORT', '5432') %>
  timeout: 5000
  username: <%= ENV.fetch('DATABASE_USER', 'postgres') %>

development:
  <<: *default
  database: cran_indexer_development

test:
  <<: *default
  database: cran_indexer_test

---
production:
  <<: *default
  database: cran_indexer_production
  password: <%= ENV["CRAN_INDEXER_DATABASE_PASSWORD"] %>
  username: cran_indexer
